# Generated by Django 3.2.3 on 2021-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_diagnostic_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
