# Generated by Django 3.2.3 on 2021-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userdetails_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='profession',
            field=models.CharField(default='PATIENT', max_length=100),
        ),
    ]
