# Generated by Django 3.2.3 on 2021-06-18 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_diagnostic'),
        ('home', '0007_userdetails_data'),
    ]

    operations = [
    ]
